### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by eVcAlex** [transistorsoft/rn-background-geolocation-demo#115]
Hey, 

When loading test geofencing in the advanced app it causes an unhandled promise rejection also when adding a geofence manually. However, it still gets added after the error but loading in the test geofences does not.

**Comment by christocracy** [comment]
You probably did not provide “Always” authorization.

See the native logs for more information.  You didn’t specify if Android or iOS.  Those are two completely different operating systems.
