### ISSUE TITLE
Android not working - NullPointerException

### ISSUE THREAD

**Issue by georgeflug** [transistorsoft/rn-background-geolocation-demo#123]
I am unable to get the latest demo working on Android. Here's what I did:

1. Cloned the repo
2. Installed dependencies with `yarn install`
3. Ran with `npx react-native run android`

The app loads but I get the stack trace below when I press any of the buttons (Advanced App, Hello World App, Edit, or View Tracking).

I was able to run this by using a commit from November, so this appears to be a recent regression. The commit 59bfb0620598d48cca360be53e4fc27c7726d864 works.

05-20 13:22:37.256  5077  5077 E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.facebook.react.uimanager.FabricViewStateManager.hasStateWrapper()' on a null object reference
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.views.textinput.ReactEditText.updateCachedSpannable(ReactEditText.java:981)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.views.textinput.ReactEditText.access$300(ReactEditText.java:75)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.views.textinput.ReactEditText$TextWatcherDelegator.onTextChanged(ReactEditText.java:1092)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.widget.TextView.sendOnTextChanged(TextView.java:11785)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.widget.TextView.setText(TextView.java:6965)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.widget.TextView.setText(TextView.java:6761)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.widget.EditText.setText(EditText.java:145)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.widget.TextView.setText(TextView.java:6713)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.widget.TextView.setEditableFactory(TextView.java:6670)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at androidx.emoji2.viewsintegration.EmojiEditTextHelper$HelperInternal19.<init>(EmojiEditTextHelper.java:268)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at androidx.emoji2.viewsintegration.EmojiEditTextHelper.<init>(EmojiEditTextHelper.java:109)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at androidx.appcompat.widget.AppCompatEmojiEditTextHelper.<init>(AppCompatEmojiEditTextHelper.java:52)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:110)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:91)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:87)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.views.textinput.ReactEditText.<init>(ReactEditText.java:126)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:180)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:81)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.view.Choreographer.doFrame(Choreographer.java:740)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:246)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at android.app.ActivityThread.main(ActivityThread.java:8550)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-20 13:22:37.256  5077  5077 E unknown:ReactNative: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

**Comment by Deadik** [comment]
same issue

**Comment by christocracy** [comment]
I pushed a fix.  Either `git pull origin master` or re-clone.

**Comment by Deadik** [comment]
thanks It works
