### ISSUE TITLE
Use async await in BackgroundGeolocation.onLocation() and BackgroundGeolocation.ready()

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/rn-background-geolocation-demo#126]
I need to use `async await` in `BackgroundGeolocation.onLocation()`. Depending on the result of a function `foo()` I either start or do not start the location tracking. However, I am having problems implementing this, because `BackgroundGeolocation.onLocation()` is not `async`, and I cannot nest `BackgroundGeolocation.ready()` into `BackgroundGeolocation.onLocation()`. This is my first approach.

        let startTracking;
        const onLocation = BackgroundGeolocation.onLocation(async location => {
            console.log('[onLocation]', location);
            startTracking = await foo(location);
        }, error => {
            ...
        });

        if (startTracking) {
            BackgroundGeolocation.ready({
                ...
            }, state => {
                if (!state.enabled) {
                    BackgroundGeolocation.start(() => {
                        ...
                    });
                }
            });
        } else {
            ...
        }

However, because `await foo(location)` is `async`, `startTracking` is always `false` when evaluated in this expression `if (startTracking) {` because its `undefined` (through my variable declaration `let startTracking;`.

I also tried this

        const onLocation = BackgroundGeolocation.onLocation(async location => {
            console.log('[onLocation]', location);
            let startTracking = await foo(location)
            if (startTracking) {
                BackgroundGeolocation.ready({
                    ...
                }, state => {
                    if (!state.enabled) {
                        BackgroundGeolocation.start(() => {
                            ...
                        });
                    }
                });
            } else {
                ...
            }
        }, error => {
            ...
        });

But this won't even start the location tracking... I assume one cannot nest `BackgroundGeolocation.onLocation()` and `BackgroundGeolocation.ready()`. 

So how would I wait with `BackgroundGeolocation.ready()` until `await foo(location)` did evaluate?

**Comment by christocracy** [comment]
What you’re trying to do does t make sense to me.

adding event listeners (eg onLocation) is like wiring up speakers to your stereo system.  Hooking up speakers is a benign thing that you do once and forget about it.

.ready() is like plugging in the AC cord to your stereo receiver.

.start() / .stop() is the [POWER] button.

Calling .ready() does not imply that music is going to start playing.   Only .start() starts the music.

you should not be calling .ready() from within an event-listener such as onLocation.

**Comment by Stophface** [comment]
Hey Chris,
thanks for your reply. I understand this, and still I am struggeling. I need to run a function with the very first location I am getting, and, depending on the outcome, keep on backgroundtracking or abort the background tracking... 

I think a workaround could be to only ask for one location, once. Is there a method implemented, that only returns one location, _without_ setting up a subscription?

**Comment by christocracy** [comment]
Setting up onLocation event is a benign action.  Completely harmless.  It merely adds a function to a List.

yes, there’s a method.  See api docs .getCurrentPosition().

you must not request a location until .ready(Config) has resolved.

**Comment by Stophface** [comment]
Thats why I call it like that

```
BackgroundGeolocation.ready({
            ...
        }, state => {
            if (!state.enabled) {
                BackgroundGeolocation.start(() => {
                    ...
                });
            }
        });
```

Thanks for the hinting to `getCurrentPosition()`, that will do it!

**Comment by christocracy** [comment]
You are not required to call .start() in .ready(Config).
