### ISSUE TITLE
Where do I set geofenceProximityRadius 

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/rn-background-geolocation-demo#128]
I wonder where I set the proximity radius for the geofences. Do I set it for each geofence 

```
BackgroundGeolocation.addGeofences([{
  identifier: "Home",
  radius: 200,
  latitude: 45.51921926,
  longitude: -73.61678581,
  notifyOnEntry: true,
  geofenceProximityRadius : 2000
}, {
  identifier: "Work",
  radius: 200,
  latitude: 45.61921927,
  longitude: -73.71678582,
  notifyOnEntry: true,
  geofenceProximityRadius : 5000
}]).then((success) => {
  console.log("[addGeofences] success");
}).catch((error) => {
  console.log("[addGeofences] FAILURE: ", error);
});
```

Or do I set it somewhere else?

**Comment by christocracy** [comment]
You are misunderstanding what geofenceProximityRadius is.

go back and read the api docs.

this is not something applied to each geofence.

In most cases, you do not even need to think about it (the default is sufficient)

**Comment by Stophface** [comment]
@christocracy I understand that you can set it somewhere, and it gets applied for all the geofences globally. From the docs, I cannot derive where to set it. Its not mentioned here https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html for example. Nor is it mentioned in the `addGeofences()` method. Setting it for each geofence like I originally suggested was probably a not really thorught through wild guess. But, I need to change the default. That is why I am asking where to set the `geofenceProximityRadius`

**Comment by christocracy** [comment]
Why is the default insufficient?

Any option which is a member of the `Config` interface in the docs, as `geofenceProximityRadius` is, is known to be provided to both `.ready(Config)` and `.setConfig(Config)`.
