### ISSUE TITLE
Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.

### ISSUE THREAD

**Issue by mgsbabu** [transistorsoft/rn-background-geolocation-demo#132]
Plugin version - 4.12.1
React native 0.68.2

Please find my build.gradle file here

import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        appCompatVersion = "1.4.2"
        googlePlayServicesLocationVersion = "20.0.0"

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:7.0.4")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {

    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            url("${project(':react-native-background-geolocation').projectDir}/libs")
        }
        maven {
            // Required for react-native-background-geolocation
            url("${project(':react-native-background-geolocation').projectDir}/libs")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

What am I missing here. I am running it DEBUG mode. I didnt generate any license file. If everything works in debug mode, i can buy the license key. When I run the debug command, the below error is happening.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - file:/Users/sridhar/fabklean/mobileapps/apps/fabkleanDriver/node_modules/react-native/android/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/sridhar/fabklean/mobileapps/apps/fabkleanDriver/node_modules/jsc-android/dist/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/sridhar/fabklean/mobileapps/apps/fabkleanDriver/node_modules/react-native-background-geolocation/android/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://www.jitpack.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :react-native-background-fetch
   > Could not find com.huawei.hms:location:6.9.0.300.
     Searched in the following locations:
       - file:/Users/sridhar/fabklean/mobileapps/apps/fabkleanDriver/node_modules/react-native/android/com/huawei/hms/location/6.9.0.300/location-6.9.0.300.pom
       - file:/Users/sridhar/fabklean/mobileapps/apps/fabkleanDriver/node_modules/jsc-android/dist/com/huawei/hms/location/6.9.0.300/location-6.9.0.300.pom
       - file:/Users/sridhar/fabklean/mobileapps/apps/fabkleanDriver/node_modules/react-native-background-geolocation/android/libs/com/huawei/hms/location/6.9.0.300/location-6.9.0.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/6.9.0.300/location-6.9.0.300.pom
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/6.9.0.300/location-6.9.0.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/6.9.0.300/location-6.9.0.300.pom
       - https://www.jitpack.io/com/huawei/hms/location/6.9.0.300/location-6.9.0.300.pom
     Required by:
         project :app > project :react-native-background-geolocation

**Comment by christocracy** [comment]
Why are you posting this at the *demo* app repo?

why do you have two identical maven repos for react-native-background-geolocation?

go back to the Setup Instructions **and read them carefully**.  You are being careless.
