### ISSUE TITLE
 How do I open the Battery Optimized Apps list?

### ISSUE THREAD

**Issue by gusilveiramp** [transistorsoft/rn-background-geolocation-demo#135]
BackgroundGeolocation.deviceSettings.show(request) it is opening the list of apps WITHOUT battery OPTIMIZATION, however I need to open the list of Apps WITH active battery OPTIMIZATION so that the user can turn off battery optimization.BackgroundGeolocation.deviceSettings.show(request);

**Comment by christocracy** [comment]
I don't think you can.
