### ISSUE TITLE
Disable Sound?

### ISSUE THREAD

**Issue by fzf** [transistorsoft/rn-background-geolocation-demo#136]
Running a release version on ios and I cannot seem to figure out how to disable background sounds. I tried changing it in Settings > Notifications but that didnt work. So I went through and tried to remove every reference to sound including the Info.plist and the `playSound(name:any)` method in `SettingsService`. Is there something I am missing?

**Comment by christocracy** [comment]
See api docs Config.debug.

The demo app also has a "Settings" screen with a simple toggle control for "Debug".

**Comment by christocracy** [comment]
You know you're posting at the Demo app repo, right?  This is not the repo for the plugin itself.

**Comment by fzf** [comment]
I realize this is the demo app, I have this running in another app that is sending events to my service. I just find your tools better then what I want to spend the time working on so wanted to try to glean from the demo app without it making sound.

**Comment by christocracy** [comment]
You just have to set `debug: false` in your Config provided to .ready.
