### ISSUE TITLE
Problem android with altitude

### ISSUE THREAD

**Issue by djangoamidala** [transistorsoft/rn-background-geolocation-demo#138]
Hello, i hope you are fine :) 

I need help about android, on IPhone the altitude is perfect, in my place it’s 53-54m of altitude, but on android it’s like 98 it’s not the same way to calculate I would like have the same way than on iPhone please. It’s important for my application 🙏 Thank you for everything

**Comment by christocracy** [comment]
Have you read the api docs Location.altitude?

**Comment by christocracy** [comment]
This is not the correct repo to post support requests for the plug-in.

this repo is the demo app.
