### ISSUE TITLE
App dont work

### ISSUE THREAD

**Issue by Borges53** [transistorsoft/rn-background-geolocation-demo#140]
(node:5040) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info A dev server is already running for this project on port 8081.
info Installing the app...

> Task :app:buildCMakeDebug[arm64-v8a] FAILED                                                                                                          
C/C++: ninja: error: Stat(rnscreens_autolinked_build/CMakeFiles/react_codegen_rnscreens.dir/C_/Users/gfalo/OneDrive/Documentos/GitHub/rn-background-geolocation-demo-master/node_modules/react-native-screens/common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderConfigShadowNode.cpp.o): Filename longer than 260 characters
178 actionable tasks: 11 executed, 167 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\gfalo\OneDrive\Documentos\GitHub\rn-background-geolocation-demo-master\android\app\.cxx\Debug\2o5i1533\arm64-v8a'
  [0/2] Re-checking globbed directories...

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\gfalo\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\Users\\gfalo\\OneDrive\\Documentos\\GitHub\\rn-background-geolocation-demo-master\\android\\app\\.cxx\\Debug\\2o5i1533\\arm64-v8a" ^      
        appmodules ^
        react_codegen_rnscreens
    from C:\Users\gfalo\OneDrive\Documentos\GitHub\rn-background-geolocation-demo-master\android\app
  ninja: error: Stat(rnscreens_autolinked_build/CMakeFiles/react_codegen_rnscreens.dir/C_/Users/gfalo/OneDrive/Documentos/GitHub/rn-background-geolocation-demo-master/node_modules/react-native-screens/common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderConfigShadowNode.cpp.o): Filename longer than 260 characters

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'. > com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\gfalo\OneDrive\Documentos\GitHub\rn-background-geolocation-demo-master\android\app\.cxx\Debug\2o5i1533\arm64-v8a' [0/2] Re-checking globbed directories... C++ build system [build] failed while executing: @echo off "C:\\Users\\gfalo\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^ -C ^ "C:\\Users\\gfalo\\OneDrive\\Documentos\\GitHub\\rn-background-geolocation-demo-master\\android\\app\\.cxx\\Debug\\2o5i1533\\arm64-v8a" ^ appmodules ^ react_codegen_rnscreens from C:\Users\gfalo\OneDrive\Documentos\GitHub\rn-background-geolocation-demo-master\android\app ninja: error: Stat(rnscreens_autolinked_build/CMakeFiles/react_codegen_rnscreens.dir/C_/Users/gfalo/OneDrive/Documentos/GitHub/rn-background-geolocation-demo-master/node_modules/react-native-screens/common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderConfigShadowNode.cpp.o): Filename longer than 260 characters * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 5s.
info Run CLI with --verbose flag for more details.

**Comment by christocracy** [comment]
did you see this?

> Filename longer than 260 characters

See here:  https://github.com/th3rdwave/react-native-safe-area-context/issues/424

**Comment by Borges53** [comment]
checking

**Comment by Borges53** [comment]
thanks, it work
