### ISSUE TITLE
Cant start background location 

### ISSUE THREAD

**Issue by Borges53** [transistorsoft/rn-background-geolocation-demo#141]
//geo.ts

`
import BackgroundGeolocation from 'react-native-background-geolocation';
import {useTaskPersistStore} from './storages/TaskStorage';
import {useAuthPersistStore} from './storages/AuthStorage';

export const configureBackgroundGeolocation = async () => {
  let tasks = useTaskPersistStore.getState().tasks;
  const userData = useAuthPersistStore.getState().user;
  const CheckBackgroundLocation =
    useAuthPersistStore.getState().checkBackgroundLocation;
  let aux = tasks.find(
    task =>
      task.job_status_ === 'inprogress' &&
      task.template_id_?.location_accuracy_ != 'none',
  );

  await BackgroundGeolocation.ready(
    {
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 5,
      stopTimeout: 5,
      // Debug
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // HTTP & Persistence
      maxDaysToPersist: 14,
      url: `${process.env.API_ENDPOINT}Geo/Sync` || 'awdads',
      autoSync: true,
      //batchSync: true,
      params: {
        user_id:
          userData?.type == 'manager'
            ? userData?.agent_id_?._id
            : userData?._id,
        // ...(!!aux ? {taskId: aux._id} : {}),
      },
      // Application
      stopOnTerminate: true,
      startOnBoot: true,
      enableHeadless: true,
      // Permissions
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title:
          "Allow {applicationName} to access this device's location even when closed or not in use.",
        message:
          'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      },
    },
    async state => {
      let checkBackgroundLocation =
        useAuthPersistStore.getState().checkBackgroundLocation;
      if (checkBackgroundLocation) {
        await BackgroundGeolocation.start();
      } else {
        await BackgroundGeolocation.stop();
      }
    },
  );
};

const isLocationEnabled = async (): Promise<boolean> => {
  const state = await BackgroundGeolocation.getState();
  if (!state.enabled) {
    return false;
  }
  return true;
};
`

PROFILE,js
`<Switch
                        value={checkBackgroundLocation}
                        thumbColor={
                          checkBackgroundLocation ? COLORS.primary : '#f4f3f4'
                        }
                        disabled={!isConnected}
                        onValueChange={async value => {
                          if (value) {
                            BackgroundGeolocation.start(
                              async () => {
                                console.log('- Start success');
                              },
                              async error => {
                                console.log('- Start failure: ', error);
                              },
                            );
                          } else {
                            console.log('STOP');
                            BackgroundGeolocation.stop();
                          }
                          setBackGroundLocation(value);
                        }}
                        trackColor={{false: '#f4f3f4', true: COLORS.primary}}
                      />`
                      --------------------------
           I call the configuration in the root of the project but when in profile I activate the geolocation it does not work, it does not send me the locations to the back and it does not log or make noise indicating that I take a location.

**Comment by christocracy** [comment]
Is this a question specifically about the demo app in this repo?

**Comment by Borges53** [comment]
Hi, no . use the demo to test if it was something wrong with the emulator but it works.

**Comment by Borges53** [comment]
It is an application that I am developing, sorry to bother but I do not understand why the background location is not activated, I tried everything.

**Comment by christocracy** [comment]
Also, please [learn to syntax highlight "fenced code blocks"](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)

If your question is not specifically about the demo app in this repo, you must post an issue at the **plugin's** github repo.

**Comment by Borges53** [comment]
sorry
