### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by vincentschroeder** [transistorsoft/rn-background-geolocation-demo#15]
When I start the xcode project following errors are shown:
![screen shot 2015-12-29 at 11 53 39](https://cloud.githubusercontent.com/assets/6410444/12033422/0b46f050-ae23-11e5-9bfc-cdbac266e170.png)

**Comment by christocracy** [comment]
Confirmed.

**Comment by christocracy** [comment]
Issue is with `react-native-mapbox-gl`.  I'll upgrade the deps...what a moving target `react-native` is...

**Comment by christocracy** [comment]
ok, close XCode, package manager and pull from master.

```
$ npm install
```

re-open XCode.  Should work now.
