### ISSUE TITLE
undefined object

### ISSUE THREAD

**Issue by texas697** [transistorsoft/rn-background-geolocation-demo#18]
getting this when trying to run

> 2016-02-12 13:15:02.976 [warn][tid:com.facebook.React.JavaScript] undefined is not an object (evaluating 'NativeModules.MapboxGLManager.mapStyles')
> 2016-02-12 13:15:02.979 [error][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'NativeModules.MapboxGLManager.mapStyles')
> 2016-02-12 13:15:03.179 [trace][tid:com.facebook.React.JavaScript] Running application "RNBackgroundGeolocationSample" with appParams: {"rootTag":1,"initialProps":{}}. **DEV** === true, development-level warning are ON, performance optimizations are OFF
> 2016-02-12 13:15:03.180 [warn][tid:com.facebook.React.JavaScript] Invariant Violation: Application RNBackgroundGeolocationSample has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
> 2016-02-12 13:15:03.180 [error][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: Application RNBackgroundGeolocationSample has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.

**Comment by christocracy** [comment]
I got this error earlier today and I noticed I've got 2 XCode projects `RNBackgroundGeolocationDemo` and `RNBackgroundGeolocationSample`.  Use `RNBackgroundGeolocationSample`.  I'll delete the other one.

**Comment by texas697** [comment]
i did try both! same thing?

**Comment by christocracy** [comment]
make sure you restart the package manager.

On Fri, Feb 12, 2016 at 2:47 PM, Rudy Sanchez <notifications@github.com>
wrote:

> i did try both! same thing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/18#issuecomment-183464180>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by texas697** [comment]
ok, deleted demo project. closed everything and reopened. same error. now before i go any further im not sure if this would have anything to do with this. when i tried to clone the project i got a error because i was getting a ssh error from the package.json. i downloaded the zip file and removed the ssh from your forked version of react-native-gmaps. everything worked. dont see this affecting anything because im not using android but need to make sure! what steps do i take next?

**Comment by christocracy** [comment]
I've upgraded to react `0.19.0`.
https://github.com/transistorsoft/react-native-background-geolocation/pull/57

**Comment by Mnjt** [comment]
Hi , I'm new learner of react native and trying to implement tracking app like this app help of it. but it's always gives error , 


![simulator screen shot sep 26 2016 5 00 24 pm](https://cloud.githubusercontent.com/assets/22446834/18832749/d940f042-840a-11e6-9ba3-18cfd993f192.png)

Xcode 



![screen shot 2016-09-26 at 5 04 18 pm](https://cloud.githubusercontent.com/assets/22446834/18832873/6330f216-840b-11e6-9e60-897eb93e0a50.png)

thank you !
