### ISSUE TITLE
When running "react-native run-android" I get several errors.

### ISSUE THREAD

**Issue by vcdflow** [transistorsoft/rn-background-geolocation-demo#19]
**I've done the following:**
Install Demo: git clone https://github.com/transistorsoft/rn-background-geolocation-demo.git
Install plugin into Demo:
cd rn-background-geolocation-demo
npm install https://git@github.com:transistorsoft/react-native-background-geolocation-android.git

**Then tried running:**
rn-background-geolocation-demo Home $** react-native run-android**

JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0191Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:14: error: package com.transistorsoft.rnbackgroundgeolocation does not exist
import com.transistorsoft.rnbackgroundgeolocation.*;
^
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:15: error: package com.oblador.vectoricons does not exist
import com.oblador.vectoricons.VectorIconsPackage;
                              ^
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:16: error: package com.rota.rngmaps does not exist
import com.rota.rngmaps.RNGMapsPackage;
                       ^
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:17: error: package com.learnium.RNDeviceInfo does not exist
import com.learnium.RNDeviceInfo.*;
^
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:42: error: cannot find symbol
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                                        ^
  symbol:   variable BuildConfig
  location: class MainActivity
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:40: error: cannot find symbol
                .addPackage(new RNDeviceInfo())         // react-native-device-info
                                ^
  symbol:   class RNDeviceInfo
  location: class MainActivity
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:39: error: cannot find symbol
                .addPackage(new RNGMapsPackage())       // react-native-gmaps
                                ^
  symbol:   class RNGMapsPackage
  location: class MainActivity
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:38: error: cannot find symbol
                .addPackage(new VectorIconsPackage())   // react-native-vector-icons
                                ^
  symbol:   class VectorIconsPackage
  location: class MainActivity
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:37: error: cannot find symbol
                .addPackage(new RNBackgroundGeolocation(this))  // <-- for background-geolocation
                                ^
  symbol:   class RNBackgroundGeolocation
  location: class MainActivity
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:34: error: cannot find symbol
        new ReactNativeMapboxGLPackage(),
            ^
  symbol:   class ReactNativeMapboxGLPackage
  location: class MainActivity
/Users/Home/AndroidProjects/rn-background-geolocation-demo/android/app/src/main/java/com/transistorsoft/rnbackgroundgeolocationsample/MainActivity.java:35: error: cannot find symbol
        new RNDeviceInfo())
            ^
  symbol:   class RNDeviceInfo
  location: class MainActivity
11 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by vcdflow** [comment]
Side note:  Tried running the iOS version and ran into it's error as well.

2016-02-18 08:35:43.657 xctest[39296:29982885] The bundle “RNBackgroundGeolocationTests” couldn’t be loaded because its executable couldn’t be located. Try reinstalling the bundle.
Program ended with exit code: 1

**Comment by christocracy** [comment]
I'm working on upgrading the demo app.  It breaks every time react
upgrades.  Pretty frustrating.

It's not a problem with my core library, it's purely the moving target of
the mechanics of react-native.

On Thu, Feb 18, 2016 at 9:37 AM, vcdflow <notifications@github.com> wrote:

> Side note: Tried running the iOS version and ran into it's error as well.
>
> 2016-02-18 08:35:43.657 xctest[39296:29982885] The bundle
> “RNBackgroundGeolocationTests” couldn’t be loaded because its executable
> couldn’t be located. Try reinstalling the bundle.
> Program ended with exit code: 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/19#issuecomment-185748550>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vcdflow** [comment]
Yikes.... Ive literally been trying to build this now for a week.  Is there ANYWAY I can get the $300 purchase that I made working?  This is Erik BTW, I emailed you 2x in the past week but no response.  :(  We are trying to build a simple Tracking App that sends location info to our web app... but obviously can't do jack right now.

**Comment by christocracy** [comment]
Sorry, about that.  Had my hands tied all month on the Cordova side (which
uses the same lib under the hood).

I'll refund your purchase.

I'll have a look ASAP.  Hard to keep up with RN.

Good news is the latest lib has some great features and fixes, including
iOS preventSuspend, elasticity for Android, location-update deferral,
improved SQLite concurrency.

On Saturday, February 27, 2016, vcdflow <notifications@github.com> wrote:

> Yikes.... Ive literally been trying to build this now for a week. Is there
> ANYWAY I can get the $300 purchase that I made working? This is Erik BTW, I
> emailed you 2x in the past week but no response. :( We are trying to build
> a simple Tracking App that sends location info to our web app... but
> obviously can't do jack right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/19#issuecomment-189578360>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Ok, I've got my the sample app booting on Android with `react-native-0.19`.  Updates coming soon.

**Comment by vcdflow** [comment]
Thanks for refund.  Look for it later today.

**Comment by christocracy** [comment]
What's your order id?

On Sat, Feb 27, 2016 at 2:41 PM, vcdflow <notifications@github.com> wrote:

> Thanks for refund. Look for it later today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/19#issuecomment-189711112>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by liamzebedee** [comment]
@christocracy if you make any progress I'd be keen to know! It's definitely related to this section of the release notes for 0.21.0:

>We've simplified how your Android apps are built. The Android binaries are now distributed via npm along with the rest of the framework (rather than Maven). This means you'll need to run react-native upgrade to upgrade you Android build (.gradle) files. This is a one-time change.

**Comment by christocracy** [comment]
Thanks.

**Comment by vcdflow** [comment]
@christocracy I saw your recent commit and wondering if the Android version can now build properly?

**Comment by christocracy** [comment]
Builds fine for me

On Wednesday, March 9, 2016, vcdflow <notifications@github.com> wrote:

> @christocracy <https://github.com/christocracy> I saw your recent commit
> and wondering if the Android version can now build properly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/19#issuecomment-194525462>
> .
>


-- 
Snet form Gmail Mobile

**Comment by fenderrex** [comment]
been at this balls to the wall for 4 days aswell fun fact google gets stumped with java debuger syntax aka hard to learn try installing all by hand eg https://github.com/oblador/react-native-vector-icons

**Comment by fenderrex** [comment]
sorry i meant to highlight the rnpm link <package name> part lol

**Comment by christocracy** [comment]
This thread is obsolete and closed.

Please post a new issue with details.
