### ISSUE TITLE
change ios markers

### ISSUE THREAD

**Issue by texas697** [transistorsoft/rn-background-geolocation-demo#21]
how can i change the red location markers with the blue polyline ? I see the functions there to do it but I do not know if that is for android or ios? or both? I uncommented the function and was getting a error from the create method.

**Comment by christocracy** [comment]
Hello again :)  I didn't put much thought into the mapping specifics yet.

Lol, I'm going to bump you again:  this is actually a question specifically about [react-native-mapbox-gl](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/API.md) API.

Let me know if you find out anything interesting.

**Comment by texas697** [comment]
OK! will head over there!
