### ISSUE TITLE
Android emulator(s) problem

### ISSUE THREAD

**Issue by geezmo** [transistorsoft/rn-background-geolocation-demo#22]
Hello Chris, and thanks for your great work.
I'm having some issue with several Android emulators - basically the demo app never updates its location after the first hit. The problem disappears with my real Android device (and with iOs emulator), so i'm wondering if there's something more I have to do to make things work on the Android emulators too. I tried with Android stock emulator, Genymotion & Xamarin, setting positions manually over telnet as well as mocking locations - but with no luck. If i have to stop using emulators and go with real devices it's fine, just checking for some precise info about it (all that i've found googling around is a bunch of contradictory info).
Thanks a lot! :-)

**Comment by christocracy** [comment]
Emulators don't have an accelerometer or gyroscope, both of which are required to determine if the device is moving.

When running in emulator, you must manually execute the method `BackgroundGeolocation.changePace(true)`

iOS uses a geofence to determine stationary-exit.

**Comment by christocracy** [comment]
If you want to simulate location on a device, I use [Locito](https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito&hl=en).

**Comment by christocracy** [comment]
Also, if you run on emulator and execute `#changePace`, the `#stopTimeout` will eventually expire, re-engaging stationary-mode, so set a large `stopTimeout`.

**Comment by christocracy** [comment]
Furthermore, when running on a device, you can simulate moving by shaking your device vigorously until the next `activityRecognitionInterval` detects an activity other than `still` with a `confidence > minimumActivityRecognitionConfidence` (default 80%)

**Comment by geezmo** [comment]
Awesome. Thanks :+1:
