### ISSUE TITLE
npm install results in remote repository access error

### ISSUE THREAD

**Issue by ontwikkelfabriek** [transistorsoft/rn-background-geolocation-demo#27]
When i follow the instructions to install the demo i get an error when i run the 'npm install' command.

![image](https://cloud.githubusercontent.com/assets/9429959/16147065/7a4138aa-3481-11e6-9505-f2fed6751ece.png)

**Comment by kristojorg** [comment]
I am seeing this same error.

**Comment by christocracy** [comment]
You're having a Github authorization issue.  Have you [uploaded your ssh key to Github](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)?

**Comment by ontwikkelfabriek** [comment]
Yes that solved that part. Why is all the git-ssh setup not needed to run all your other samples/demos?

Now I get a new error:
![image](https://cloud.githubusercontent.com/assets/9429959/16483669/b640c986-3eb5-11e6-95f9-cbc4722e8963.png)

**Comment by christocracy** [comment]
As the error message says "please ensure you have latest version of node
and npm".

The error is from Mapbox, not my plugin.

I just installed the demo from scratch yesterday so the problem is with
your platform.

On Thursday, June 30, 2016, ontwikkelfabriek <notifications@github.com>
wrote:

> Yes that solved that part. Why is all the git-ssh setup not needed to run
> all your other samples/demos?
>
> Now I get a new error:
> [image: image]
> <https://cloud.githubusercontent.com/assets/9429959/16483669/b640c986-3eb5-11e6-95f9-cbc4722e8963.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/27#issuecomment-229609096>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l6S11yVbH0qDGQz0n4SZqiLyGTstks5qQ4xYgaJpZM4I4M1k>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
I just refactored the demo app a bit and got it booted with latest react-native `0.29.0`.
