### ISSUE TITLE
Errors uploading to app store

### ISSUE THREAD

**Issue by mrondon** [transistorsoft/rn-background-geolocation-demo#28]
Hello, i'm trying to test the battery consumption using this app on my phone.

However, when i try to upload it to the app store (to use it with TestFlight), i'm getting these errors:

`
ERROR ITMS-90087: "Unsupported Architectures. The executable for RNBackgroundGeolocationSample.app/Frameworks/Mapbox.framework contains unsupported architectures '[x86_64, i386]'."

ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "RNBackgroundGeolocationSample.app/Frameworks/Mapbox.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'RNBackgroundGeolocationSample.app/Frameworks/Mapbox.framework/Mapbox' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
`

I have almost no experience in debugging with xcode, but the app works well in the simulator, i don't know if this is actually an issue or if i am doing something wrong. Any ideas?

**Comment by christocracy** [comment]
I'll have a look when I return from vacation next week.

On Friday, June 24, 2016, Max Rondon <notifications@github.com> wrote:

> Hello, i'm trying to test the battery consumption using this app on my
> phone.
>
> However, when i try to upload it to the app store (to use it with
> TestFlight), i'm getting these errors:
>
> `
> ERROR ITMS-90087: "Unsupported Architectures. The executable for
> RNBackgroundGeolocationSample.app/Frameworks/Mapbox.framework contains
> unsupported architectures '[x86_64, i386]'."
>
> ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle
> "RNBackgroundGeolocationSample.app/Frameworks/Mapbox.framework" isn’t
> consistent with the Mach-O in the main bundle. The main bundle Mach-O
> contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O
> contains X86_64ALL(machine code). Verify that all of the targets for a
> platform have a consistent value for the ENABLE_BITCODE build setting."
>
> ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at
> 'RNBackgroundGeolocationSample.app/Frameworks/Mapbox.framework/Mapbox' does
> not have proper segment alignment. Try rebuilding the app with the latest
> Xcode version."
> `
>
> I have almost no experience in debugging with xcode, but the app works
> well in the simulator, i don't know if this is actually an issue or if i am
> doing something wrong. Any ideas?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/28>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l_2lhIo480LeJqhyejuNz-wld9z1ks5qO08igaJpZM4I9b38>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
The problem you're having is related to **MapBox**.  I didn't add the [Run Script phase](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md#3-adding-the-script) for MapBox.  If you want to upload this demo app to Apple, you need to follow add the [MapBox Run-script phase](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md#3-adding-the-script).

**Comment by JayeshPoriya** [comment]
Hi
I use IQKeyboardManager with Carthage but when I submit the app on App Store I face some issue. 
Can anybody help me to sort out this issue.
![screen shot 2018-01-12 at 3 05 16 pm](https://user-
![screen shot 2018-01-12 at 3 05 22 pm](https://user-images.githubusercontent.com/16848686/34874651-f8362dd0-f7bf-11e7-8f2e-a74bbc42ea00.png)
images.githubusercontent.com/16848686/34874644-ed36dee8-f7bf-11e7-8b08-e130d82c0547.png)
