### ISSUE TITLE
Simulate Location & Settings Missing from Xcode & App

### ISSUE THREAD

**Issue by peterpme** [transistorsoft/rn-background-geolocation-demo#29]
Hey,

Great work on this project!
I'm checking out the demo, but all I see is the map with a "State" button. I don't see the settings.

In Xcode, I don't see "Simulate Location" with "Highway Drive".

See screenshots below.

Thanks!

![image](https://cloud.githubusercontent.com/assets/1211905/16812352/55ca2aec-48f2-11e6-8302-b40b957ee2cc.png)

![image](https://cloud.githubusercontent.com/assets/1211905/16812336/36776c86-48f2-11e6-9fd6-3db40d24a205.png)

**Comment by christocracy** [comment]
It's in the Simulator menu.

On Wed, Jul 13, 2016 at 1:07 PM, Peter Piekarczyk <notifications@github.com>
wrote:

> Hey,
>
> Great work on this project!
> I'm checking out the demo, but all I see is the map with a "State" button.
> I don't see the settings.
>
> In Xcode, I don't see "Simulate Location" with "Highway Drive".
>
> See screenshots below.
>
> Thanks!
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1211905/16812352/55ca2aec-48f2-11e6-8302-b40b957ee2cc.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1211905/16812336/36776c86-48f2-11e6-9fd6-3db40d24a205.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/29>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l2RVvF6Qd5DOvi81veuoFjFsKm6Eks5qVRtHgaJpZM4JLo59>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by peterpme** [comment]
Thanks!
