### ISSUE TITLE
Undefined is not an object (evaluating 'RNBackgroundGeolocation.getSate')

### ISSUE THREAD

**Issue by Mnjt** [transistorsoft/rn-background-geolocation-demo#32]
Hi , I'm new learner of react native and trying to implement tracking app like this app help of it. but it's always gives error ,
1. Undefined is not an object (evaluating 'RNBackgroundGeolocation.getSate')
2. Cannot read property 'getState' of undefined. 

plz help me 

![simulator screen shot sep 26 2016 5 00 24 pm](https://cloud.githubusercontent.com/assets/22446834/18833399/04f0dba0-840e-11e6-89dd-f3d142ae7ac1.png)

thank you!

**Comment by christocracy** [comment]
did you follow the instructions exactly?

```
$ git clone https://github.com/transistorsoft/rn-background-geolocation-demo.git
$ cd rn-background-geolocation-demo
$ npm install  <----------------- did you do this?
```

**Comment by Mnjt** [comment]
yes , according to :  https://github.com/transistorsoft/rn-background-geolocation-demo 
 


![screen shot 2016-09-26 at 6 05 12 pm](https://cloud.githubusercontent.com/assets/22446834/18834559/3fbace02-8414-11e6-93fa-31020b5070e8.png)

**Comment by christocracy** [comment]
Try re-cloning the repo and following the setup instructions from scratch.

**Comment by Mnjt** [comment]
Now , it's work properly 👍  
some changes in RCTWebSocket.m 

line no. 1337 :  (void)SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);

line no. 496 : (void)SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);

Thank you so much 👍

**Comment by christocracy** [comment]
Yea, that seems to be an issue with [react-native and XCode 8](https://github.com/facebook/react-native/issues/8108)
