### ISSUE TITLE
Error when running demo on Xcode / iOS 10 / iPhone 7 PLUS

### ISSUE THREAD

**Issue by tomeriksen** [transistorsoft/rn-background-geolocation-demo#33]
After  carefully double-checking the install process and also reading up on the other reported issues I can't get the demo to work. Hopefully I'm doing something wrong. I would appreciate the help:

Here is the install:
```
$ cd
$ cd Documents/14-Utveckling/
$ git clone https://github.com/transistorsoft/rn-background-geolocation-demo.git
...
$ cd rn-background-geolocation-demo/
$ npm install

```
Then I open this file

![finder](https://cloud.githubusercontent.com/assets/1772518/19867871/e8621144-9fa5-11e6-8eed-1cca82f50783.png)
 
Then ignoring the warnings I just hit RUN. Which results in this error.

![skarmavbild 2016-10-31 kl 20 13 34](https://cloud.githubusercontent.com/assets/1772518/19868018/8835c4cc-9fa6-11e6-8968-f5820284670e.png)

**Comment by tomeriksen** [comment]
Restarting the computer solved it. Probably because I was running another react project prior to this.

**Comment by christocracy** [comment]
You probably just need to terminate the console.
