### ISSUE TITLE
not found: RNBackgroundFetch+AppDelegate.m

### ISSUE THREAD

**Issue by kinergy** [transistorsoft/rn-background-geolocation-demo#36]
I followed the instructions to run the demo and right off the bat I get this error in XCode:
> clang: error: no such file or directory: '/Users/.../rn-background-geolocation-demo/node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch+AppDelegate.m'
clang: error: no input files

Any thoughts as to what needs fixing?
I'm using XCode 8.2

**Comment by christocracy** [comment]
I'll check it out.  I know what's going on

**Comment by christocracy** [comment]
I just booted it successfully from a fresh clone.  Are you *sure* you did
```
$ npm install
```

The file `RNBackgroundFetch+AppDelegate.m` must exist as show here:
![](https://www.dropbox.com/s/tzdvixsevn735bk/Screenshot%202016-12-18%2008.35.11.png?dl=1)

If you *did* do `npm install`, perhaps the XCode project is linked relative to *my* machine.  Execute the final step in the `background-fetch` [install instructions](https://github.com/transistorsoft/react-native-background-fetch/blob/master/docs/INSTALL.md#backgroundfetch-appdelegate-extension)

**Comment by kinergy** [comment]
My starting state was this:
![image](https://cloud.githubusercontent.com/assets/1538985/21465079/dec42cee-c958-11e6-8b73-7daa1ec309a1.png)

I had already installed the NPM packages and I noticed that your package.json file is actually missing the RNBackgroundFetch lib, so all I had to do is execute:
`npm install react-native-background-fetch --save`

However, now, it looks like Lumberjack is missing:
![image](https://cloud.githubusercontent.com/assets/1538985/21465082/fccc95aa-c958-11e6-96ed-2a71372692c3.png)
I tried the obvious, installing CocoaPods and then trying `pot install CocoaLumberjack` but that complained about a missing Podfile. Any thoughts?

**Comment by christocracy** [comment]
The demo all doesn't use cocoapods.

It should just work.  I'll have a look when I get back after xmas

**Comment by kinergy** [comment]
Running this fixed it:
`npm i cocoa-lumberjack --save`
