### ISSUE TITLE
:react-native-background-geolocation:processReleaseResources FAILED

### ISSUE THREAD

**Issue by AugustoAleGonZhipCode** [transistorsoft/rn-background-geolocation-demo#39]
```
Execution failed for task ':react-native-background-geolocation:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Augusto\AppData\Local\Android\Sdk\build-tools\25.0.2\aapt.exe'' finished with non-zero exit value 1
```

I am currently have this error when I tried to compile in my Android version. I already imported the react-native-background-geolocation-android plugin. I thought that was my laggy internet, but it seems the same error:

`:react-native-background-geolocation:mergeReleaseResources
AAPT out(205359196) : No Delegate set : lost message:Done
AAPT out(577055186) : No Delegate set : lost message:Done
AAPT out(430665241) : No Delegate set : lost message:Done
AAPT out(1036836727) : No Delegate set : lost message:Done
AAPT out(577055186) : No Delegate set : lost message:Crunching C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable-xxhdpi\abc_ic_voice_search_api_mtrl_alpha.png
AAPT out(577055186) : No Delegate set : lost message:Crunching C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable-xhdpi\abc_ic_clear_mtrl_alpha.png
AAPT out(2074997215) : No Delegate set : lost message:Done
AAPT out(2051713316) : No Delegate set : lost message:Done
AAPT out(1772367467) : No Delegate set : lost message:Done
AAPT out(2074997215) : No Delegate set : lost message:Done
AAPT out(577055186) : No Delegate set : lost message:Crunching C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable-xxhdpi\abc_btn_radio_to_on_mtrl_000.png
AAPT out(430665241) : No Delegate set : lost message:Done
AAPT out(289740522) : No Delegate set : lost message:Done
AAPT out(1036836727) : No Delegate set : lost message:Done
AAPT out(1036836727) : No Delegate set : lost message:Done
AAPT out(348092343) : No Delegate set : lost message:Done
AAPT out(335973046) : No Delegate set : lost message:Done
AAPT out(289740522) : No Delegate set : lost message:Done
AAPT out(577055186) : No Delegate set : lost message:Crunching C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable-xxxhdpi\abc_btn_switch_to_on_mtrl_00001.9.png
AAPT out(577055186) : No Delegate set : lost message:Crunching single PNG file: C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable-xxxhdpi\abc_btn_switch_to_on_mtrl_00001.9.png
AAPT out(577055186) : No Delegate set : lost message:   Output file: C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\res\merged\release\drawable-xxxhdpi\abc_btn_switch_to_on_mtrl_00001.9.png
AAPT out(577055186) : No Delegate set : lost message:Done
AAPT err(348092343): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-hdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1036836727): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-mdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(430665241): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(2051713316): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(577055186): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-mdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1772367467): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(205359196): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(335973046): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-hdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(289740522): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-mdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(2074997215): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xhdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(289740522): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-hdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(577055186): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(430665241): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1036836727): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xhdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(2074997215): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1036836727): C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
:react-native-background-geolocation:processReleaseManifest
:react-native-background-geolocation:processReleaseResources
Unknown source file : warning: string 'catalyst_debugjs' has no default translation.
Unknown source file : warning: string 'catalyst_element_inspector' has no default translation.
Unknown source file : warning: string 'catalyst_jsload_error' has no default translation.
Unknown source file : warning: string 'catalyst_jsload_message' has no default translation.
Unknown source file : warning: string 'catalyst_jsload_title' has no default translation.
Unknown source file : warning: string 'catalyst_reloadjs' has no default translation.
Unknown source file : warning: string 'catalyst_settings' has no default translation.
Unknown source file : warning: string 'catalyst_settings_title' has no default translation.
C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable\common_google_signin_btn_icon_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal_background').
C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable\common_google_signin_btn_icon_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal_background').
C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable\common_google_signin_btn_text_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal_background').
C:\rn-background-geolocation-demo\node_modules\react-native-background-geolocation-android\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable\common_google_signin_btn_text_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal_background').

:react-native-background-geolocation:processReleaseResources FAILED`

This is what it appears. I don't know exactly what to do? I already clean my file in Android Studio, and still I have the same issue.

**Comment by christocracy** [comment]
I would start by checking my Android SDK Manager and install updates.  Install latest build tools.

**Comment by AugustoAleGonZhipCode** [comment]
I already solved it. It is some dummy long path issue on Windows 10. What I did was setting the longpath to true.

**Comment by codeboros** [comment]
@AugustoAleGonZhipCode how can i config the longpath?
