### ISSUE TITLE
undefined is not an object (evaluating 'RNBackgroundGeolocation.configure') 

### ISSUE THREAD

**Issue by Sharnw** [transistorsoft/rn-background-geolocation-demo#40]
Trying to run on android (with paid licence).

Have tried both my own build, a swell as a fresh clone of the 'rn-background-geolocation-demo'.

Same result after recloning like in similar issue: https://github.com/transistorsoft/rn-background-geolocation-demo/issues/32

Have run npm install, npm start (server currently running), and react-native run-android.

Have made sure npm has installed 'react-native-background-geolocation' package.

```
import BackgroundGeolocation from "react-native-background-geolocation";
global.BackgroundGeolocation = BackgroundGeolocation;
```

Still unable to use RNBackgroundGeolocation when run in android. "undefined is not an object (evaluating 'RNBackgroundGeolocation.configure') "

Some help would be very much appreciated :)

**Comment by christocracy** [comment]
I just did a fresh clone of this repo.

```
$ npm install
$ react-native run-android
```
works.

**Comment by Sharnw** [comment]
It's working for me too now. react-native is bizarre at times.

**Comment by christocracy** [comment]
Perhaps you didn't kill your dev server *before* `$ react-native run-android`?

**Comment by christocracy** [comment]
I'm currently refactoring the demo app.  There may be UI bugs.  I just ripped out the **hated** MapBox and replaced with `react-native-maps` last night.
