### ISSUE TITLE
RNBackgroundGeolocation.getSensors is not a function

### ISSUE THREAD

**Issue by botteu** [transistorsoft/rn-background-geolocation-demo#45]
Trying to run the demo in iOS simulator. 
On macOS Sierra 10.12.6.
Xcode version 8.3.1

Steps to reproduce:

1. git clone https://github.com/transistorsoft/rn-background-geolocation-demo.git
2. cd rn-background-geolocation-demo
3. npm install
4. react-native run-ios

![image](https://user-images.githubusercontent.com/164277/30265754-720d79ae-96dd-11e7-9133-97e09c81681a.png)

**Comment by christocracy** [comment]
`getSensors` method appeared in version `2.8.5`.  What version of `react-native-background-geolocation` do you have installed?

The SampleApp requires [`^2.9.0`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/package.json#L17)

**Comment by christocracy** [comment]
I just cloned the repo and performed the setup steps without issue.

Did you terminate your React Packager before running `$ react-native run-ios`?

**Comment by botteu** [comment]
It works now. Probably had a React Packager running… Thank you for the speedy reply!
