### ISSUE TITLE
package-lock.json causing versioning problems

### ISSUE THREAD

**Issue by peterlau** [transistorsoft/rn-background-geolocation-demo#47]
Hi there,
I'm evaluating your product for a project we're working on and had some trouble getting the demo to work.  I was getting a bunch of cryptic errors such as

```
bgGeo.getSensors is not a function. 
```

among numerous others.

Turns out the package-lock.json embedded in the demo repo is causing `react-native-background-geolocation@2.8.3` to be used by default when `npm install` is executed. 

The `master` branch of the demo, however, expects `2.9.x`. It would be easier for the next person if either `package-lock.json` was removed or updated, or RELEASE tags added to the demo repo.

**Comment by christocracy** [comment]
There you go.  `package-lock.json` removed.

**Comment by peterlau** [comment]
Thanks. That's fast turnaround!
