### ISSUE TITLE
How to modify?

### ISSUE THREAD

**Issue by alexbom** [transistorsoft/rn-background-geolocation-demo#48]
Hello!
It's great job, man.
I'm thinking about using in my projects.
But i don't understand, how to modify the example?
Can i start something like Live or Hot Reload to play with the source code?
Or i have to buy before?

**Comment by christocracy** [comment]
This is just the demo of app of the [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation).

You're free to use any of this RN app.

Using the Android plugin requires purchasing a license.  It will work in DEBUG builds only.

**Comment by alexbom** [comment]
Sorry, i didn't understand. Can i use hot or live reload in debug build?
If i can, how to run it?
"npm start" doesn't work. And after "react-native run-android" i can't run hot or live reload.
Actually, i even can't see changes if i write some code to index.android.js or components/HomeView.js and make build again with "react-native run-android".
So could you explain, how to work with it?

**Comment by christocracy** [comment]
There's nothing special you need to do.  This is a standard react-native app.

```
$ react-native run-android
```
- Shake device for dev menu -> Enable live reload
- Edit code in `/components`.

**Comment by alexbom** [comment]
No. It's not working that simple way. I made installation instructions twice.
My different react native project is familliar with hot reloading.
But when i make changes in source code of your example, hot reloading doesn't refresh the output.
Application is working, but is not changeble.

**Comment by christocracy** [comment]
I have no idea.  It works for me.

**Comment by christocracy** [comment]
Are you *terminating* the react-native dev server *before* launching the demo app?
