### ISSUE TITLE
need to override http upload ...

### ISSUE THREAD

**Issue by alamrezoanul** [transistorsoft/rn-background-geolocation-demo#50]
Hi Author,

1. I need to override or send the tracking data to my custom server rather than "tracker.transistorsoft.com". How can I do that? I've tried to find it out but couldn't.
2. Is it possible to get the location name as well with lat, lng? e.g. there is pin for starbucks in my current location of the app, is it possible to get that starbucks name also?

Need your help please.

Thanks in advance.
Riad.

**Comment by christocracy** [comment]
You're free to override any config options [here](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/components/HomeView.js#L362)
