### ISSUE TITLE
Cannot add geofence via BackgroundGeolocation.addGeofence

### ISSUE THREAD

**Issue by SuTran** [transistorsoft/rn-background-geolocation-demo#56]
### Expected Behavior

1. Geofence can be shown in the map after added
2. Geofence can be submitted to [background-geolocation-console](https://github.com/transistorsoft/background-geolocation-console)

### Current Behavior

![Issue Capture](https://i.imgur.com/fvO5Cba.gif)

### Steps to Reproduce

1. Open AdvancedApp screen
2. Long press on the map to open 'Add Geofence' screen
3. Field the form then click 'Add'
4. The form closed, nothing happen

### Detailed Description

There is one change I made to the source, since we want to setup our own server to process the geolocation data. So I pulled the code from [background-geolocation-console](https://github.com/transistorsoft/background-geolocation-console), start the server from there. Changed the `TRACKER_HOST` to `http://xxx:9000/locations`. The integration gone well, since the web can track the data sent from mobile.
I tried to debug this behavior. Follow the GeofenceView.js line 74. The success callback was triggered, console printed: `- addGeofence success: undefined`

Thank for your time. If you need more information, please comment below. I really appreciate your help!

**Comment by christocracy** [comment]
If you've configured `debug: true` and your hear the sound *doo-dee* after adding the geofence, it worked.  The thing about the plugin's geofencing system is that it only activates those within `geofenceProximityRadius` (default `1000` meters).

If you've added a geofence > `geofenceProximityRadius` meters from your current location, you won't see it on the map.

- Try adding a geofence within `geofenceProximityRadius` meters from your current location.
- Try increasing `geofenceProximityRadius` (eg: `10000`).  You will see it appear.
- Observe the logcat: `$ adb logcat -s TSLocationManager`
```
02-07 09:21:51.847 22130 22208 I TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create]
02-07 09:21:51.847 22130 22208 I TSLocationManager:   ✅  Aaa
02-07 09:21:52.089 22130 22149 D TSLocationManager: [c.t.locationmanager.geofence.a a]
02-07 09:21:52.089 22130 22149 D TSLocationManager: ╔═════════════════════════════════════════════
02-07 09:21:52.089 22130 22149 D TSLocationManager: ║ TSGeofenceManager found 0/1 within 1000 meters
02-07 09:21:52.089 22130 22149 D TSLocationManager: ╠═════════════════════════════════════════════
02-07 09:21:52.089 22130 22149 D TSLocationManager: ╚═════════════════════════════════════════════
```

**Comment by christocracy** [comment]
See [here for an animation](https://www.transistorsoft.com/shop/products/assets/images/background-geolocation-infinite-geofencing.gif) of how the plugin's geofencing system works.  As new geofences are discovered within `geofenceProximityRadius` they become activated; As old one fall out of `geofenceProximityRadius`, they disappear.  These activated / deactivated geofences are informed to you via [`geofenceschange`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#geofenceschange) event.  

Also see Wiki [Geofencing](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/geofencing.md)

**Comment by SuTran** [comment]
Thank Christocracy for you support. Now I can add geofence follow you instructions.
