### ISSUE TITLE
Build Failed after npm install

### ISSUE THREAD

**Issue by AleskiWeb** [transistorsoft/rn-background-geolocation-demo#58]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find :tsbackgroundfetch:.
     Required by:
         project :app
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Required by:
         project :app > project :react-native-background-fetch
```
if I open the application in Android Studio I see

```
Error:Failed to resolve: com.transistorsoft:tsbackgroundfetch:+
```

As far as I can tell I have followed all the instructions. I'm using, according to `build.gradle`:

`compileSdkVersion 26`
`buildToolsVersion "26.0.2"`
`'com.android.tools.build:gradle:2.2.3'`

OS: Windows 10

EDIT: Oh and I can confirm i have `~/../node_modules/react-native-background-fetch` installed and in the `node_modules` folder

**Comment by christocracy** [comment]
```
$ git pull origin master
$ rm -rf node_modules
$ npm install
```

I posted an update to `background-fetch` (`2.4.0`) yesterday, which packages `tslocationmanager` as a Maven repo.

This change requires a small change to how the plugin is installed and the demo has not yet been updated with this change.

I've locked the demo to version `"react-native-background-fetch": "~2.3.0"` (was `^2.3.0`)

**Comment by christocracy** [comment]
FYI, here's the install instructions for [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch/blob/master/docs/INSTALL-LINK-ANDROID.md#open_file_folder-androidbuildgradle)

The change is simply `flatDirs` becomes `maven url`
