### ISSUE TITLE
undefined is not an object (evaluating 'context.changedBits')

### ISSUE THREAD

**Issue by amirey** [transistorsoft/rn-background-geolocation-demo#65]
Hi there

I followed your instructions - cloned the repo, npm install in the directory, react-native run-android. Everything seem to work fine - build and install of debug APK, but my Android device (physical Nexus 5X) shows the red screen with the error undefined is not an object (evaluating 'context.changedBits'). I have a screenshot of the error attached.

I have tried successfully an older version of the demo app in the past and was hoping to finally become a customer with the new version.

Thanks!
![screenshot_20180515-134719](https://user-images.githubusercontent.com/6405356/40036004-38e77ed6-5848-11e8-87b5-b7febc45e9fc.png)

**Comment by amirey** [comment]
I should probably add more information:
Dev machine OS - Windows 10
Node - v8.11.1
npm - 5.6.0

**Comment by christocracy** [comment]
Did you restart your dev server before booting this SampleApp?

**Comment by christocracy** [comment]
Actually, after a fresh clone, I see this issue.  I had to upgrade `react-navigation` to version `2.0.0`.  I probably messed something up in the conversion.

**Comment by christocracy** [comment]
Ok, weird.  I upgraded to `react-native @ 0.54.4` and it boots now.  Must be an issue with latest `react-navigation @ 2.0.1`.

Pull on master (or re-clone).  
```
$ rm -rf node_modules
$ npm install
```

**Comment by amirey** [comment]
Seems to have done the trick. Thanks, Chris!
