### ISSUE TITLE
Username is incorrect

### ISSUE THREAD

**Issue by 31laxbdog** [transistorsoft/rn-background-geolocation-demo#69]
Whenever I enter any username, it says that it needs to be alphanumeric and does not let me continue. Is this a bug? Additionally there are some notifications behind the popup indicating "RTCBridge required dispatch_sync" and "Failed prop type: invalid props.style key 'NativeBase' supplied to 'View'". Can someone help me interpret this?

**Comment by 31laxbdog** [comment]
Username error was a user error because I thought the website link had to be included.

**Comment by christocracy** [comment]
First I’ve heard of this.  I haven’t touched the demo in months.
