### ISSUE TITLE
NativeBase Error

### ISSUE THREAD

**Issue by blake-edwards** [transistorsoft/rn-background-geolocation-demo#70]
There are some error notifications indicating "RTCBridge required dispatch_sync" and "Failed prop type: invalid props.style key 'NativeBase' supplied to 'View' Bad Object". Can someone help me interpret this? 
<img width="400" alt="screen shot 2018-07-31 at 11 14 01 pm" src="https://user-images.githubusercontent.com/9518852/43499012-7fa89ca4-9517-11e8-8377-63ece05837a4.png">
<img width="390" alt="screen shot 2018-07-31 at 11 14 13 pm" src="https://user-images.githubusercontent.com/9518852/43499013-816dfe30-9517-11e8-879f-23eb809321ea.png">

**Comment by 31laxbdog** [comment]
@christocracy I am using the IOS 6 simulator. Yes it looks similar to that error. Not really sure where to go in the code to fix it though!

**Comment by christocracy** [comment]
Did you really say *”iOS 6”*?

**Comment by 31laxbdog** [comment]
Yes, I have an iPhone 6..

**Comment by christocracy** [comment]
Yes, but not *iOS 6*.  I didn’t start developing this plugin until iOS 7 and the min supported iOS is now 8.4.

**Comment by 31laxbdog** [comment]
Not ios 6! I believe it is ios 8!

**Comment by christocracy** [comment]
Make sure it’s >= iOS 8.4.

**Comment by 31laxbdog** [comment]
Okay I will check and reply back to you! Thank you for replying promptly!
