### ISSUE TITLE
The Sample App does not Archive on Xcode

### ISSUE THREAD

**Issue by onewaydsp** [transistorsoft/rn-background-geolocation-demo#72]
I opened the .xcworkspace in Xcode and tried to archive; however, there are many build errors.   I am using Xcode 9.4.1

duplicate symbol _OBJC_CLASS_$_RCTLinkingManager in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTLinkingManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTLinking.a(RCTLinkingManager.o)

duplicate symbol _OBJC_METACLASS_$_RCTLinkingManager in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTLinkingManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTLinking.a(RCTLinkingManager.o)

duplicate symbol _OBJC_CLASS_$_RCTSettingsManager in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTSettingsManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTSettings.a(RCTSettingsManager.o)

duplicate symbol _OBJC_IVAR_$_RCTSettingsManager._bridge in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTSettingsManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTSettings.a(RCTSettingsManager.o)

duplicate symbol _OBJC_IVAR_$_RCTSettingsManager._defaults in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTSettingsManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTSettings.a(RCTSettingsManager.o)

duplicate symbol _OBJC_IVAR_$_RCTSettingsManager._ignoringUpdates in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTSettingsManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTSettings.a(RCTSettingsManager.o)

duplicate symbol _OBJC_METACLASS_$_RCTSettingsManager in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTSettingsManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTSettings.a(RCTSettingsManager.o)

duplicate symbol _OBJC_CLASS_$_RCTFileReaderModule in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFileReaderModule.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTFileReaderModule.o)

duplicate symbol _OBJC_IVAR_$_RCTFileReaderModule._bridge in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFileReaderModule.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTFileReaderModule.o)

duplicate symbol _OBJC_METACLASS_$_RCTFileReaderModule in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFileReaderModule.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTFileReaderModule.o)

duplicate symbol _OBJC_CLASS_$_RCTBlobManager in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTBlobManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTBlobManager.o)

duplicate symbol _OBJC_IVAR_$_RCTBlobManager._blobs in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTBlobManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTBlobManager.o)

duplicate symbol _OBJC_IVAR_$_RCTBlobManager._blobsMutex in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTBlobManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTBlobManager.o)

duplicate symbol _OBJC_IVAR_$_RCTBlobManager._bridge in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTBlobManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTBlobManager.o)

duplicate symbol _OBJC_IVAR_$_RCTBlobManager._queue in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTBlobManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTBlobManager.o)

duplicate symbol _OBJC_METACLASS_$_RCTBlobManager in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTBlobManager.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTBlob.a(RCTBlobManager.o)

duplicate symbol _OBJC_CLASS_$_RCTFrameAnimation in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFrameAnimation.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTAnimation.a(RCTFrameAnimation.o)

duplicate symbol _OBJC_IVAR_$_RCTFrameAnimation._animationCurrentTime in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFrameAnimation.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTAnimation.a(RCTFrameAnimation.o)

duplicate symbol _OBJC_IVAR_$_RCTFrameAnimation._animationHasBegun in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFrameAnimation.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTAnimation.a(RCTFrameAnimation.o)

duplicate symbol _OBJC_IVAR_$_RCTFrameAnimation._animationHasFinished in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFrameAnimation.o)

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libRCTAnimation.a(RCTFrameAnimation.o)

duplicate symbol _OBJC_IVAR_$_RCTFrameAnimation._animationId in:

    /Users/onewaydsp/Library/Developer/Xcode/DerivedData/BGGeolocation-fkiygrkmcqhxstfgognmmonhqlcn/Build/Intermediates.noindex/ArchiveIntermediates/BGGeolocation/BuildProductsPath/Release-iphoneos/libReact.a(RCTFrameAnimation.o)

**Comment by christocracy** [comment]
Some help please...
- OS Version
- XCode Version

**Comment by christocracy** [comment]
Sorry, I see your XCode version

**Comment by christocracy** [comment]
When you cloned this demo repo, did you:
```
$ npm install
```

**Comment by onewaydsp** [comment]
Yea I ran npm install... also I am on 10.13.6

**Comment by christocracy** [comment]
I got it to archive:
![](https://dl.dropboxusercontent.com/s/ztj6667aqhzisko/Screenshot%202018-10-02%2009.27.53.png?dl=1)

However, I had to **delete (remove references)** everything in the `React` libs in `/Libraries`, since those are already installed in `/Pods/DevelopmentPods/React`.

![](https://dl.dropboxusercontent.com/s/0zzh45a7gpmgxva/Screenshot%202018-10-02%2009.28.58.png?dl=1)

After doing that, I had a build error coming from the `Test` target.  I deleted the `Test` target and it worked.  I'll be posting a new version to this repo soon, using latest React Native `0.57.1`

**Comment by christocracy** [comment]
Instead of deleting libs in `/Libraries`, I found [this works](https://github.com/auth0/react-native-lock/issues/3#issuecomment-358103352) too.

*ios/Podfile*
```diff
target 'BGGeolocation' do  
  # Pods for BGGeolocation
  .
  .
  .
+  post_install do |installer|
+      installer.pods_project.targets.each do |target|
+          if target.name == "React"
+              target.remove_from_project
+          end
+      end
+  end
end

**Comment by christocracy** [comment]
Merged to master.  Re-clone the repo and start from scratch.

**Comment by onewaydsp** [comment]
Thanks guys!

Regards,

Andrew
