### ISSUE TITLE
This rn background geolocation tracking package is not working after generating the release build in ios 10.1

### ISSUE THREAD

**Issue by softsathian** [transistorsoft/rn-background-geolocation-demo#78]
This rn background geolocation tracking package is not working after generating the release build

**Comment by christocracy** [comment]
Am I supposed to guess whether you’re talking about iOS or Android?

**Comment by christocracy** [comment]
Oh, there it is in the loooong title.  

Define “not working” with evidence.

**Comment by softsathian** [comment]
i have tried in iOS.

**Comment by christocracy** [comment]
I await your evidence of "not working".
