### ISSUE TITLE
Error on react-native run-android

### ISSUE THREAD

**Issue by slegal** [transistorsoft/rn-background-geolocation-demo#79]
Hi, 
When I try to run the application I have the following error on the screen of my android simulator. Can you help me?

The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module `./index` from `C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\react-native\scripts/.`. Indeed, none of these files exist:<br> &nbsp;* `C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\react-native\scripts\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp;* `C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\react-native\scripts\index\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)<br> &nbsp; &nbsp;at ResolutionRequest.resolveDependency (C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)<br> &nbsp; &nbsp;at C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\metro\src\lib\transformHelpers.js:261:42<br> &nbsp; &nbsp;at Server.&lt;anonymous&gt; (C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\metro\src\Server.js:1038:41)<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at asyncGeneratorStep (C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\metro\src\Server.js:99:24)<br> &nbsp; &nbsp;at _next (C:\Users\TEMP.DESKTOP-2BVAOLC.001\Documents\rn-background-geolocation-demo\node_modules\metro\src\Server.js:119:9)</pre>
</body>
</html>

processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764

**Comment by christocracy** [comment]
Have you terminated any rn dev servers you may have running previously?

**Comment by slegal** [comment]
Yes this is the only one

**Comment by christocracy** [comment]
Did you npm install after cloning?

**Comment by slegal** [comment]
No I used npm install

**Comment by christocracy** [comment]
I just cloned this demo repo from scratch:
```
$ npm install
$ react-native run-android
```
It works.

**Comment by christocracy** [comment]
Try running it on a real device.  The problem is on your end.

**Comment by slegal** [comment]
I tried on a real device but the problem persists

**Comment by slegal** [comment]
Problem finally solved. I re-installed react-native. Thanks for your reactivity!
