### ISSUE TITLE
Project does not run, instructions incomplete

### ISSUE THREAD

**Issue by scarlac** [transistorsoft/rn-background-geolocation-demo#80]
Following the instructions to `npm install` and `react-native run-ios` results in an app that displays this issue:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/895369/59787551-9384cf80-927e-11e9-8a1f-d6378908b9e6.png">

The error is `null is not an object (evaluating 'RNFetchBlob.DocumentDir')`

This issue is a variation of this (with null instead of undefined):
https://github.com/wkh237/react-native-fetch-blob/issues/454

**Workaround**
Following the instructions from the github ticket, I ran `pod update` which fixed the issue. This is unfortunately a very widespread problem in the react native community due to the fetch-blob library being very buggy. I see variations on this issue on multiple projects, including my own.

**Solution**
README should be updated to reflect this required `cd ios && pod update` step, or repository should have this run and updated pods should be committed.

**Other info**
Result of `react-native info`:
```
10:38:54 ~/jobs/rn-background-geolocation-demo ⚡️ react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 6.16 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - ~/.nvm/versions/node/v11.2.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by christocracy** [comment]
I’ve never heard of RNFetchBlob before.

**Comment by scarlac** [comment]
My apologies. After investigating the demo project I can confirm there is no use of it. It turned out that another instance of the metro bundler was running. After killing it and re-trying it worked. The `pod update` was probably a coincidental fix. Closing.
