### ISSUE TITLE
Can't run the app in the Xcode Version 10.2.1 (10E1001)

### ISSUE THREAD

**Issue by GeekChao** [transistorsoft/rn-background-geolocation-demo#81]
The error is shown in the below screenshot. Thank you.

<img width="2004" alt="Screen Shot 2019-07-10 at 1 28 37 PM" src="https://user-images.githubusercontent.com/10861987/60990547-aab35c00-a316-11e9-8793-67b97ff2277a.png">

**Comment by christocracy** [comment]
After cloning the repo, did you not run `$ yarn install` (or if you prefer npm `$ npm install`)?

**Comment by GeekChao** [comment]
I did npm install, otherwise I will even failed to build the app. This above issue happens right after launching the app in a real iphone. And I also noticed the xcode doesn't launch Metro Bundler automatically. By the way, I checked the doc, but I can't find anything related with ios local notification. And the 'playSound' seems not work in either background mode or suspend mode. Thank you.

**Comment by christocracy** [comment]
>And I also noticed the xcode doesn't launch Metro Bundler automatically

*Edit Scheme -> Build Configuration [ Debug][v]*
![](https://dl.dropbox.com/s/61c6vmwwqxzypl8/Screenshot%202019-07-10%2013.49.40.png?dl=1)

**Comment by GeekChao** [comment]
Thank you, it helps. This same error "'t.AlertIOS.prompt'" still pops up, but the app works.

**Comment by christocracy** [comment]
Ok, I reproduced this in a fresh clone.  Was missing a few changes while upgrading to 0.60 after comparing with changes against a fresh new hello world
- Changes to `AppDelegate.h` / `AppDelegate.m`.
- New run-script build-phase.
- `react-native` change `PromptIOS` -> `Prompt`.

Destroy your clone.  Re-clone and `$ npm install`.  Should work now.

**Comment by GeekChao** [comment]
Thank you so much. 
One more question: is it possible for me to trigger local notification in ios and android with customized text and sound inside 'onHeartbeat' or 'onLocation'  callback when the app is in the background, suspended, and terminated mode? This is a crucial feature to decide if we purchase the license or not.

**Comment by christocracy** [comment]
> is it possible for me to trigger local notification in ios and android

Yes, You're free to do whatever you wish in your `#onHeartbeat` / `#onLocation` event-handlers.but this plugin provides no API for that.  This is a location-tracking plugin.  Simply implement a 3rd-party lib dedicated to showing notifications, such as [react-native-notifications](https://github.com/wix/react-native-notifications). 

>customized text and sound

Do not use this plugin as your sound-library.  Perhaps something like [react-native-media-player](https://github.com/mybigday/react-native-media-player)

**Comment by christocracy** [comment]
And for the Android *terminated* case, you'll want to implement the [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode) to show notifications / play sounds.

**Comment by GeekChao** [comment]
Hi Chris:

	Thank you for clarification and patience.

	   When the app is in the background mode, I tried to do bluetooth scanning in the callback of onHeartbeat, but it is not like what you said —  free to do whatever you wish in your #onHeartbeat / #onLocation event-handlers. 

	I also tried the below four tasks, that is, console.log, playSound, ble scan, and vibrate separately in the background mode. 

       Only Console.log works. I would appreciate that if you have any insights of bluetooth scanning in onHeartbeat callback.

Regards,
Kevin

**Comment by christocracy** [comment]
try performing your actions within a [`startBackgroundTask`](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#startbackgroundtask) block.

**Comment by GeekChao** [comment]
> try performing your actions within a [`startBackgroundTask`](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#startbackgroundtask) block.

Thank you
