### ISSUE TITLE
Getting error: duplicate class: com.transistorsoft.backgroundgeolocation.react.ReactNativeFlipper

### ISSUE THREAD

**Issue by eranmore** [transistorsoft/rn-background-geolocation-demo#88]
I'm trying to run the Demo application - but I get this error.

Steps I ran:
>  git clone https://github.com/transistorsoft/rn-background-geolocation-demo.git
>  cd rn-background-geolocation-demo
>  yarn install
** no errors up to this point...

>  react-native run-android

=> produces compilation error:
error: duplicate class: com.transistorsoft.backgroundgeolocation.react.ReactNativeFlipper

/rn-background-geolocation-demo/android/app/src/debug/java/com/transistorsoft/backgroundgeolocation/react/ReactNativeFlipper.java:28: error: duplicate class: com.transistorsoft.backgroundgeolocation.react.ReactNativeFlipper
public class ReactNativeFlipper {
       ^

Any ideas?
Thanks in advance :)

**Comment by christocracy** [comment]
Somebody else mentioned something about this recently.  I'll clone and make a fresh build tomorrow.

**Comment by christocracy** [comment]
Fixed and merged to master.
