### ISSUE TITLE
Demo App Doesn't Compile for iOS

### ISSUE THREAD

**Issue by objectiveSee** [transistorsoft/rn-background-geolocation-demo#89]
I cloned this repo today and tried to get it working. I ran `npm install`, removed the pod lock file and run `pod install`.  Getting some Xcode compiler errors such as the one below. It appears to be related to the Yoga pod's `Yoga-prefix.pch` file missing.

```
🚐 react-native --version
react-native-cli: 2.0.1
react-native: 0.62.1
```

Build Error (sample, there's many):

```
<built-in>:1:10: fatal error: '/Users/username/Downloads/rn-background-geolocation-demo/ios/Pods/Target Support Files/Yoga/Yoga-prefix.pch' file not found
#include "/Users/username/Downloads/rn-background-geolocation-demo/ios/Pods/Target Support Files/Yoga/Yoga-prefix.pch"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Screenshot from Xcode:
<img width="1560" alt="Screen Shot 2020-05-12 at 10 07 31 AM" src="https://user-images.githubusercontent.com/1684106/81723997-85acdf80-9438-11ea-9098-dd81d8793056.png">

**Comment by objectiveSee** [comment]
Here's the log output from running the `ios` npm script in VScode. https://gist.github.com/objectiveSee/7f2a92f0f04579094b81174405d08002

**Comment by christocracy** [comment]
Oops, `ios/Pods` is supposed to be in `.gitignore`.

```
$ cd ios
$ rm -rf Pods
$ rm Podfile.lock
$ pod install
```

**Comment by objectiveSee** [comment]
Hey @christocracy thanks for the quick reply! It's working now from Xcode. I ran your instructions but I'm still getting errors when running from the CLI, but since it works from Xcode then it's not a big deal for me. Gonna dig into this example code!

**Comment by christocracy** [comment]
The sample code probably doesn't follow modern RN best-practices.  It's more designed for my own field-testing purposes.  the *Advanced App* has a lot of extra complexity to manage the *Settings* screen.
