### ISSUE TITLE
Event is not triggered when the app is terminated

### ISSUE THREAD

**Issue by swmd** [transistorsoft/rn-background-geolocation-demo#91]
Hello,

I built and ran the demo app on my iPhone 7 Plus. It works well in both foreground and backend modes.
But when I terminate the app, it doesn't trigger any event. As far as I understand, it should trigger an event either when I walked a certain amount of meters or when I didn't move for 15 mins.
Please correct me if I am wrong.

I terminated the app and waited for hours but nothing is logged in the metro bundler nor any data is sent to the tracking server.

Can anyone explain how this app is supposed to work when it's terminated?

**Comment by christocracy** [comment]
Build iOS for release so that the app doesn’t try to fetch the bundle from the local dev server when it reboots in the background to resume tracking.  Or test in the simulator.

**Comment by swmd** [comment]
@christocracy thank you for your quick reply. I will try using the release build.
However I have another issue with the simulator. 
I copied the code(the part for configuration) from the demo app and pasted it in my own project. I keep getting the error in the screenshot. Please check it here:
![image](https://user-images.githubusercontent.com/12961158/83063565-a2642c80-a060-11ea-97eb-77ac3c338fd3.png)

Do you have any idea on this issue?

FYI I have followed the instructions properly to set up both react-nativebackground-geolocation and react-native-background-fetch packages.

**Comment by christocracy** [comment]
iOS doesn’t support the new BGTaskScheduler api in simulator.

**Comment by christocracy** [comment]
See [README](https://github.com/transistorsoft/react-native-background-fetch/blob/master/README.md#new-bgtaskscheduler-api-for-ios-13) at background-fetch

**Comment by swmd** [comment]
As I said, I just copied the code from the demo app. The demo app seems to be working, isn't it?

Here is my code for BackgroundFetch configuration:

`configureBackgroundFetch = () => {
    // [Optional] Configure BackgroundFetch.
    BackgroundFetch.configure({
      minimumFetchInterval: 15, // <-- minutes (15 is minimum allowed)
      stopOnTerminate: false, // <-- Android-only,
      startOnBoot: true, // <-- Android-only
      enableHeadless: true,
      requiresCharging: false,
      requiredNetworkType: BackgroundFetch.NETWORK_TYPE_NONE,
      requiresDeviceIdle: false,
      requiresBatteryNotLow: false,
      requiresStorageNotLow: false
    }, async (taskId) => {
      console.log('[BackgroundFetch event]:', taskId);
      // One could optionally request a location here with #getCurrentPosition
      //
      BackgroundFetch.finish(taskId);
    }, (error) => {
      console.log('[js] RNBackgroundFetch failed to start')
    });

    BackgroundFetch.scheduleTask({
      taskId: 'com.transistorsoft.customtask',
      delay: 5000,
      stopOnTerminate: false,
      enableHeadless: true,
      periodic: true,
      forceAlarmManager: true
    }).then((success) => {
      console.log('[BackgroundFetch scheduleTask] success');
    }).catch((error) => {
      console.warn('[BackgroundFetch scheduleTask] ERROR: ', error);
    });
  };
`

Could you tell me what is causing that issue?
Do I need BackgroundFetch at all in order to trigger the event when the app is terminated?

**Comment by christocracy** [comment]
You do not need to implement `BackgroundFetch` in your Javascript in order to test `react-native-background-geolocation`.  Delete all references to `BackgroundFetch`.

**Comment by swmd** [comment]
Could you let me know why you used it in the demo app?

**Comment by christocracy** [comment]
Because I like to test both of my plugins at the same time.

**Comment by swmd** [comment]
Okay. Makes sense.

Which method of BackgroundGeolocation is used to run a specific task when the app is terminated?
I want to send the location data to the server even when the app is not running and is in the stationary state. Currently I am using onHeartbeat() but it doesn't work well.

**Comment by christocracy** [comment]
>I want to send the location data to the server even when the app is not running and is in the stationary state. Currently I am using onHeartbeat() but it doesn't work well.

For iOS, forget about it.  Sometimes, what you want is simply *impossible* due to constraints of the OS.
