### ISSUE TITLE
iOS Build error: event2/event-config.h file not found (with workaround)

### ISSUE THREAD

**Issue by LucaBlackDragon** [transistorsoft/rn-background-geolocation-demo#97]
**System info:**
- Xcode 12.3
- Node.js 14.15.0

**Sequence of commands:**
```shell
git clone https://github.com/transistorsoft/rn-background-geolocation-demo.git
cd rn-background-geolocation-demo
npm install
npx react-native run-ios # build error :(
# ok let's try the suggested workaround from the README:
cd ios
rm Podfile.lock
pod install
cd ..
# fingers crossed...
npx react-native run-ios # build error again :(
```

**Error:**
`'event2/event-config.h' file not found`
The build error occurs in the Flipper-Folly library (by Facebook).
I was able to reproduce the same error by opening the project with Xcode and building from there.

**Workaround:**
After some googling, I found [this stackoverflow](https://stackoverflow.com/questions/66019068/event2-event-config-h-file-not-found) and edited `ios/Podfile` like this:

```diff
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BGGeolocation' do

  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  
  target 'BGGeolocationTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
-  use_flipper!
+ use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end

end
```

With this change, the build succeded.
(I also had to enable "Build Active Architecture Only" inside Xcode to actually launch the app in the emulator)

**Comment by flutterq** [comment]
[[Solved] ‘event2/event-config.h’ file not found in React-Native
](https://exerror.com/event2-event-config-h-file-not-found/)

**Comment by christocracy** [comment]
Demo has been completely rebuilt.
